# Generated by Django 3.2.16 on 2024-12-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_product_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_field',
            new_name='text',
        ),
    ]
